[package]
name = "timestamp-parser"
version = "0.1.0"
authors = ["Ravikumar Alluboyina <ravi@robinsystems.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
